#!/usr/bin/env python3
"""
init_stubs.py
─────────────
Creates  cards/XXXX_<word>.json  stub files from words.py.

Safe to re-run: already-generated cards (status != "pending") are
never overwritten — only genuinely missing stubs are created.

Usage:
    python3 init_stubs.py
"""

import json, re
from pathlib import Path
from words import WORDS

CARDS_DIR = Path("cards")
CARDS_DIR.mkdir(exist_ok=True)

def slug(word: str) -> str:
    """Turn a Montenegrin word into a safe filename fragment."""
    s = word.lower()
    s = re.sub(r"[^a-zA-ZčćžšđČĆŽŠĐa-ž\-]", "_", s)
    s = re.sub(r"_+", "_", s).strip("_")
    return s[:40]

created = skipped = 0

for idx, (montenegrin, russian, pos, context_ru, dalle_prompt) in enumerate(WORDS, start=1):
    filename = CARDS_DIR / f"{idx:04d}_{slug(montenegrin)}.json"

    if filename.exists():
        data = json.loads(filename.read_text("utf-8"))
        if data.get("status") != "pending":
            skipped += 1
            continue
        # overwrite only if it's still a blank pending stub
        # (don't clobber partial work)

    stub = {
        # ── Identity ──────────────────────────────────────────────
        "id":           idx,
        "montenegrin":  montenegrin,
        "russian":      russian,
        "pos":          pos,
        "context_ru":   context_ru,
        "dalle_prompt": dalle_prompt,

        # ── Status ────────────────────────────────────────────────
        # pending → generating → done
        "status":       "pending",

        # ── Front (query) side ────────────────────────────────────
        # queryText is assembled from russian + pos + context_ru
        # queryImage1 is the DALL-E JPEG, stored as base64 string
        "query_text":   f"{russian}\n[{pos}  {context_ru}]",
        "image_b64":    None,          # filled by generate_card.py

        # ── Back (answer) side ────────────────────────────────────
        # Full grammar + forms + 3 sentences, generated by GPT-4o-mini
        "answer_text":  None,          # filled by generate_card.py
        "audio_b64":    None,          # TTS of the montenegrin word, mp4/aac

        # ── Metadata ──────────────────────────────────────────────
        "error":        None,
    }

    filename.write_text(json.dumps(stub, ensure_ascii=False, indent=2), "utf-8")
    created += 1

print(f"✓ Created {created} stubs, skipped {skipped} already-processed cards.")
print(f"  Cards directory: {CARDS_DIR.resolve()}")
